### PR TITLE
example 05-csrf to show csrf protection on iso-call

### PR DESCRIPTION
**Pull request by hero78119**

### CODE REVIEW

**Comment by zordius** [comment]
Thank you for your contribution! But some eslint error should be fixed before merge, please check this CI log: https://travis-ci.org/zordius/iso-call/jobs/61170149

**Comment by hero78119** [comment]
fixed! Note with thanks :))

**Comment by zordius** [comment]
Another small issue is : we using cookie for both server -> client CSRF token delivery and client -> server CSRF token validation, which means we do not prevent CSRF attack in this example.

**Comment by hero78119** [comment]
Yes... it might be good to store secret in session while keep token in cookie. Let me modify with better example.

**Comment by zordius** [comment]
Well, I think it is better to use different way to deliver CSRF token and verification. These ways will be better:

A.   server -> client cookie ; then client -> server header
B.   server -> client cookie ; then client -> server form field
C.   server -> client HTML attribute ; then client -> server cookie

When you use cookie on both, which means the request will be valid automatically every time.

**Comment by hero78119** [comment]
Finally I figure out that it's still possible to delegate token verification to csurf by customized req validation function. With that, the csrf token can be passed to client with `server -> client HTML attribute` and verified `client -> server rpc payload field` :))

**Comment by zordius** [comment]
Thank you for your contribution!

**Pull request merged**
